import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { saveGlobalConfig, DEFAULT_MODEL } from "../config";
import { chat as realChat } from "../openrouter/client";
import { parseDepths } from "../review/depth";
import { detectStack, type StackInfo } from "./detect-stack";
import type { SquanchyConfig } from "../types";

const MAX_FILES = 2000;
const KEY_FILES = ["package.json", "tsconfig.json", "Dockerfile", "bunfig.toml", "go.mod", "pyproject.toml"];

export interface InitFlags {
  openrouterKey?: string;
  githubToken?: string;
  model?: string;
  depth?: string;
}

export interface InitDeps {
  repoDir: string;
  globalDir: string;
  env: Record<string, string | undefined>;
  flags: InitFlags;
  /** returns null when non-interactive */
  promptSecret: (label: string) => Promise<string | null>;
  chatFn?: typeof realChat;
  log?: (msg: string) => void;
}

export function listRepoFiles(repoDir: string): string[] {
  try {
    const proc = Bun.spawnSync(["git", "ls-files", "--cached", "--others", "--exclude-standard"], {
      cwd: repoDir,
    });
    if (proc.exitCode === 0) {
      const out = proc.stdout.toString().trim();
      if (out) return out.split("\n").slice(0, MAX_FILES);
    }
  } catch {
    // fall through to glob
  }
  const glob = new Bun.Glob("**/*");
  const files: string[] = [];
  for (const f of glob.scanSync({ cwd: repoDir, onlyFiles: true, dot: false })) {
    if (f.startsWith("node_modules/") || f.startsWith(".git/")) continue;
    files.push(f);
    if (files.length >= MAX_FILES) break;
  }
  return files;
}

function buildTree(files: string[], maxLines = 120): string {
  const entries = new Set<string>();
  for (const f of files) {
    const parts = f.split("/");
    if (parts.length <= 2) entries.add(f);
    else entries.add(parts.slice(0, 2).join("/") + "/...");
    if (entries.size >= maxLines) break;
  }
  return [...entries].sort().join("\n");
}

export function buildContextMd(stack: StackInfo, summary: string): string {
  return [
    "<!-- generated by squanchy init; regenerate anytime with `squanchy init` -->",
    "# Repository context",
    "",
    "## Detected stack",
    "",
    "```json",
    JSON.stringify(stack, null, 2),
    "```",
    "",
    "## Summary",
    "",
    summary.trim(),
    "",
  ].join("\n");
}

export async function runInit(deps: InitDeps): Promise<void> {
  const log = deps.log ?? ((m: string) => console.log(m));
  const chatFn = deps.chatFn ?? realChat;
  const { repoDir, globalDir, env, flags } = deps;

  // 1. resolve secrets: flags > env > interactive prompt
  let orKey = flags.openrouterKey ?? env.OPENROUTER_API_KEY;
  if (!orKey) orKey = (await deps.promptSecret("OpenRouter API key")) ?? undefined;
  if (!orKey) throw new Error("No OpenRouter API key given (flag, env OPENROUTER_API_KEY, or prompt)");
  let ghToken = flags.githubToken ?? env.GITHUB_TOKEN;
  if (!ghToken) ghToken = (await deps.promptSecret("GitHub personal token (for CLI use)")) ?? undefined;
  if (!ghToken) log("note: no GitHub token provided; `squanchy review` will need GITHUB_TOKEN later");

  const globalCfg: Partial<SquanchyConfig> = { openrouterApiKey: orKey };
  if (ghToken) globalCfg.githubToken = ghToken;
  saveGlobalConfig(globalDir, globalCfg);
  log(`saved secrets to ${join(globalDir, "config.json")} (mode 600)`);

  // 2. repo defaults (non-secret, committed)
  const model = flags.model ?? DEFAULT_MODEL;
  const depths = parseDepths(flags.depth ?? "vulnerabilities,major");
  mkdirSync(join(repoDir, ".squanchy"), { recursive: true });
  writeFileSync(
    join(repoDir, ".squanchy", "config.json"),
    JSON.stringify({ defaultModel: model, defaultDepths: depths }, null, 2) + "\n",
  );
  log(`wrote ${join(repoDir, ".squanchy", "config.json")}`);

  // 3. explore repo
  const files = listRepoFiles(repoDir);
  const pkgPath = join(repoDir, "package.json");
  let pkg: unknown = null;
  if (existsSync(pkgPath)) {
    try {
      pkg = JSON.parse(readFileSync(pkgPath, "utf8"));
    } catch {
      pkg = null;
    }
  }
  const stack = detectStack(files, pkg);
  log(`detected stack: ${stack.languages.join(", ") || "unknown"} (${files.length} files)`);

  // 4. one LLM call to summarize the repo for future reviews
  const keyFileContents = KEY_FILES.map((kf) => {
    const p = join(repoDir, kf);
    if (!existsSync(p)) return "";
    const content = readFileSync(p, "utf8");
    if (content.length > 8000) return `## ${kf} (truncated)\n${content.slice(0, 8000)}`;
    return `## ${kf}\n${content}`;
  })
    .filter(Boolean)
    .join("\n\n");

  const system =
    "Summarize this repository's tech stack, architecture, and conventions a code reviewer must know. " +
    "Concise (<400 words), markdown, no preamble.";
  const user = [
    `# Detected stack\n\`\`\`json\n${JSON.stringify(stack, null, 2)}\n\`\`\``,
    `# File tree\n\`\`\`\n${buildTree(files)}\n\`\`\``,
    keyFileContents ? `# Key files\n${keyFileContents}` : "",
  ]
    .filter(Boolean)
    .join("\n\n");

  const chatArgs: Parameters<typeof chatFn>[0] = {
    apiKey: orKey,
    model,
    system,
    user,
    temperature: 0.3,
  };
  const summary = await chatFn(chatArgs);

  writeFileSync(join(repoDir, ".squanchy", "context.md"), buildContextMd(stack, summary));
  log(`wrote ${join(repoDir, ".squanchy", "context.md")} (commit this file)`);

  log("\nnext steps:");
  log("  squanchy review <pr-url>                 # report mode (terminal only)");
  log("  squanchy review <pr-url> --mode review   # post review comments on the PR");
}
