import { existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { z } from "zod";
import { DEFAULT_MAX_STEPS, DEFAULT_MODEL, saveGlobalConfig } from "../config";
import { chat as realChat } from "../openrouter/client";
import { fetchModelOptions } from "../openrouter/models";
import { DEFAULT_DEPTHS, parseDepths } from "../review/depth";
import type { Depth, SquanchyConfig } from "../types";
import { detectStack, type StackInfo } from "./detect-stack";
import {
  plainReporter,
  type AskInit,
  type ExistingSecrets,
  type InitAnswers,
  type InitPromptState,
  type Reporter,
} from "./prompts";

const MAX_FILES = 2000;
const KEY_FILES = ["package.json", "tsconfig.json", "Dockerfile", "bunfig.toml", "go.mod", "pyproject.toml"];

export interface InitFlags {
  openrouterKey?: string;
  githubToken?: string;
  model?: string;
  depth?: string;
  maxSteps?: number;
}

export interface InitDeps {
  repoDir: string;
  globalDir: string;
  env: Record<string, string | undefined>;
  flags: InitFlags;
  /** when true, collect settings via askInit; otherwise resolve from flags/env/existing config only */
  interactive: boolean;
  askInit: AskInit;
  fetchModels?: (apiKey: string) => Promise<Awaited<ReturnType<typeof fetchModelOptions>>>;
  report?: Reporter;
  chatFn?: typeof realChat;
}

const GlobalFileSchema = z.object({
  openrouterApiKey: z.string().optional(),
  githubToken: z.string().optional(),
});

const RepoFileSchema = z.object({
  defaultModel: z.string().optional(),
  defaultDepths: z.array(z.string()).optional(),
  maxSteps: z.number().int().positive().optional(),
});

export function readExistingSecrets(
  globalDir: string,
  env: Record<string, string | undefined>,
): ExistingSecrets | null {
  const path = join(globalDir, "config.json");
  const file = existsSync(path) ? GlobalFileSchema.parse(JSON.parse(readFileSync(path, "utf8"))) : {};
  const openrouterApiKey = env.OPENROUTER_API_KEY ?? file.openrouterApiKey;
  const githubToken = env.GITHUB_TOKEN ?? file.githubToken;
  if (!openrouterApiKey && !githubToken) return null;
  const source = env.OPENROUTER_API_KEY ? "environment" : path;
  return { openrouterApiKey, githubToken, source };
}

export function readRepoDefaults(repoDir: string): { model: string; depths: Depth[]; maxSteps: number } {
  const path = join(repoDir, ".squanchy", "config.json");
  const file = existsSync(path) ? RepoFileSchema.parse(JSON.parse(readFileSync(path, "utf8"))) : {};
  return {
    model: file.defaultModel ?? DEFAULT_MODEL,
    depths: file.defaultDepths ? parseDepths(file.defaultDepths.join(",")) : [...DEFAULT_DEPTHS],
    maxSteps: file.maxSteps ?? DEFAULT_MAX_STEPS,
  };
}

/** flags > env > existing stored secrets > error; used when not interactive. */
export function resolveNonInteractive(
  flags: InitFlags,
  env: Record<string, string | undefined>,
  existing: ExistingSecrets | null,
  defaults: { model: string; depths: Depth[]; maxSteps: number },
): InitAnswers {
  const openrouterApiKey = flags.openrouterKey ?? env.OPENROUTER_API_KEY ?? existing?.openrouterApiKey;
  if (!openrouterApiKey) {
    throw new Error(
      "No OpenRouter API key available: pass --openrouter-key, set OPENROUTER_API_KEY, or run `squanchy init` interactively",
    );
  }
  const githubToken = flags.githubToken ?? env.GITHUB_TOKEN ?? existing?.githubToken;
  const secretsChanged = Boolean(flags.openrouterKey || flags.githubToken);
  return {
    openrouterApiKey,
    githubToken,
    secretsChanged,
    saveGlobal: secretsChanged,
    model: flags.model ?? defaults.model,
    depths: flags.depth ? parseDepths(flags.depth) : defaults.depths,
    maxSteps: flags.maxSteps ?? defaults.maxSteps,
  };
}

export function listRepoFiles(repoDir: string): string[] {
  try {
    const proc = Bun.spawnSync(["git", "ls-files", "--cached", "--others", "--exclude-standard"], {
      cwd: repoDir,
    });
    if (proc.exitCode === 0) {
      const out = proc.stdout.toString().trim();
      if (out) return out.split("\n").slice(0, MAX_FILES);
    }
  } catch {
    // fall through to glob
  }
  const glob = new Bun.Glob("**/*");
  const files: string[] = [];
  for (const f of glob.scanSync({ cwd: repoDir, onlyFiles: true, dot: false })) {
    if (f.startsWith("node_modules/") || f.startsWith(".git/")) continue;
    files.push(f);
    if (files.length >= MAX_FILES) break;
  }
  return files;
}

function buildTree(files: string[], maxLines = 120): string {
  const entries = new Set<string>();
  for (const f of files) {
    const parts = f.split("/");
    if (parts.length <= 2) entries.add(f);
    else entries.add(parts.slice(0, 2).join("/") + "/...");
    if (entries.size >= maxLines) break;
  }
  return [...entries].sort().join("\n");
}

export function buildContextMd(stack: StackInfo, summary: string): string {
  return [
    "<!-- generated by squanchy init; regenerate anytime with `squanchy init` -->",
    "# Repository context",
    "",
    "## Detected stack",
    "",
    "```json",
    JSON.stringify(stack, null, 2),
    "```",
    "",
    "## Summary",
    "",
    summary.trim(),
    "",
  ].join("\n");
}

function stackLineOf(stack: StackInfo, fileCount: number): string {
  const parts = [...stack.languages, stack.packageManager, stack.testFramework, ...stack.frameworks.slice(0, 3)];
  const shown = parts.filter(Boolean).slice(0, 5).join(" / ") || "unknown stack";
  return `${shown} (${fileCount} files)`;
}

export async function runInit(deps: InitDeps): Promise<void> {
  const report: Reporter = deps.report ?? plainReporter;
  const chatFn = deps.chatFn ?? realChat;
  const { repoDir, globalDir, env, flags } = deps;

  // 1. scan the repo first (fast) so the user sees immediate feedback
  const files = listRepoFiles(repoDir);
  const pkgPath = join(repoDir, "package.json");
  let pkg: unknown = null;
  if (existsSync(pkgPath)) {
    try {
      pkg = JSON.parse(readFileSync(pkgPath, "utf8"));
    } catch {
      pkg = null;
    }
  }
  const stack = detectStack(files, pkg);

  // 2. gather current state: stored secrets + repo defaults + flag overrides
  const existing = readExistingSecrets(globalDir, env);
  const defaults = readRepoDefaults(repoDir);
  const state: InitPromptState = {
    existing,
    currentModel: flags.model ?? defaults.model,
    currentDepths: flags.depth ? parseDepths(flags.depth) : defaults.depths,
    currentMaxSteps: flags.maxSteps ?? defaults.maxSteps,
    stackLine: stackLineOf(stack, files.length),
    locked: {
      credentials: Boolean(flags.openrouterKey && flags.githubToken),
      model: Boolean(flags.model),
      depths: Boolean(flags.depth),
    },
  };

  // 3. resolve answers (interactive prompts or flags/env/config)
  const answers = deps.interactive
    ? await deps.askInit(state, { fetchModels: deps.fetchModels ?? fetchModelOptions })
    : resolveNonInteractive(flags, env, existing, defaults);

  // 4. persist credentials when they are new and the user asked to save them
  if (answers.secretsChanged && answers.saveGlobal) {
    const globalCfg: Partial<SquanchyConfig> = { openrouterApiKey: answers.openrouterApiKey };
    if (answers.githubToken) globalCfg.githubToken = answers.githubToken;
    saveGlobalConfig(globalDir, globalCfg);
    report.info(`saved credentials to ${join(globalDir, "config.json")} (mode 600)`);
  }
  if (!answers.githubToken) {
    report.info("note: no GitHub token configured; `squanchy review` will need GITHUB_TOKEN");
  }

  // 5. repo config (non-secret, committed)
  mkdirSync(join(repoDir, ".squanchy"), { recursive: true });
  const configPath = join(repoDir, ".squanchy", "config.json");
  writeFileSync(
    configPath,
    JSON.stringify(
      { defaultModel: answers.model, defaultDepths: answers.depths, maxSteps: answers.maxSteps },
      null,
      2,
    ) + "\n",
  );
  report.info(`wrote ${configPath} (commit this file)`);

  // 6. LLM pass to summarize the repo (the slow step — keep the user informed)
  const keyFileContents = KEY_FILES.map((kf) => {
    const p = join(repoDir, kf);
    if (!existsSync(p)) return "";
    const content = readFileSync(p, "utf8");
    if (content.length > 8000) return `## ${kf} (truncated)\n${content.slice(0, 8000)}`;
    return `## ${kf}\n${content}`;
  })
    .filter(Boolean)
    .join("\n\n");

  const system =
    "Summarize this repository's tech stack, architecture, and conventions a code reviewer must know. " +
    "Concise (<400 words), markdown, no preamble.";
  const user = [
    `# Detected stack\n\`\`\`json\n${JSON.stringify(stack, null, 2)}\n\`\`\``,
    `# File tree\n\`\`\`\n${buildTree(files)}\n\`\`\``,
    keyFileContents ? `# Key files\n${keyFileContents}` : "",
  ]
    .filter(Boolean)
    .join("\n\n");

  report.start(`generating repository context with ${answers.model}`);
  const summary = await chatFn({
    apiKey: answers.openrouterApiKey,
    model: answers.model,
    system,
    user,
    temperature: 0.3,
  });
  report.stop("repository context generated");

  const contextPath = join(repoDir, ".squanchy", "context.md");
  writeFileSync(contextPath, buildContextMd(stack, summary));
  const kb = (statSync(contextPath).size / 1024).toFixed(1);
  report.info(`wrote ${contextPath} (${kb} KB — commit this file)`);

  report.done(
    [
      "next steps:",
      "  squanchy review <pr-url>                 # report mode (terminal only)",
      "  squanchy review <pr-url> --mode review   # post review comments on the PR",
    ].join("\n"),
  );
}
